name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scalaversion: ["2.10.6", "2.12.3"]
    env:
      SBT_VERSION: ${{ matrix.scalaversion == '2.10.6' && '0.13.16' || '1.0.2' }}
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v5

      # MiMa is not run for the sbt 0.13.x artifact because there is no version
      # of sbt-mima that works with sbt 1.5.x and for Scala 2.10.x.
      - name: MiMa
        if: matrix.scalaversion != '2.10.6'
        run: sbt "++${{ matrix.scalaversion }}" "^^${{ env.SBT_VERSION }}" mimaReportBinaryIssues

      - name: Build
        run: sbt "++${{ matrix.scalaversion }}" "^^${{ env.SBT_VERSION }}" publishLocal
      - name: Test
        run: sbt "++${{ matrix.scalaversion }}" "^^${{ env.SBT_VERSION }}" scripted
